// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shivakala.Infrastructure.Data;

#nullable disable

namespace Shivakala.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ShivakalaDbContext))]
    [Migration("20260602000000_AddManagementSystem")]
    partial class AddManagementSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            // Existing entities are preserved from previous snapshot.
            // New entities added by this migration are tracked here.

            modelBuilder.Entity("Shivakala.Core.Entities.AppUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("FullName").HasColumnType("TEXT");
                b.Property<string>("Mobile").HasColumnType("TEXT");
                b.Property<string>("PhotoUrl").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<string>("PasswordResetToken").HasColumnType("TEXT");
                b.Property<DateTime?>("PasswordResetExpiry").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
                b.Property<DateTime?>("LastLoginDate").HasColumnType("TEXT");
                b.Property<int?>("TeacherId").HasColumnType("INTEGER");
                b.Property<int?>("StudentId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.ToTable("AppUsers");
            });

            modelBuilder.Entity("Shivakala.Core.Entities.Teacher", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Mobile").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Email").HasColumnType("TEXT");
                b.Property<string>("Qualification").HasColumnType("TEXT");
                b.Property<string>("Specialisation").HasColumnType("TEXT");
                b.Property<string>("PhotoUrl").HasColumnType("TEXT");
                b.Property<string>("Address").HasColumnType("TEXT");
                b.Property<string>("EmployeeCode").HasColumnType("TEXT");
                b.Property<decimal?>("MonthlySalary").HasColumnType("TEXT");
                b.Property<DateTime>("JoiningDate").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<string>("AdminNotes").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Teachers");
            });

            modelBuilder.Entity("Shivakala.Core.Entities.Batch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Standard").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Medium").HasColumnType("TEXT");
                b.Property<int>("MaxStrength").HasDefaultValue(30).HasColumnType("INTEGER");
                b.Property<string>("Room").HasColumnType("TEXT");
                b.Property<string>("TimingSlot").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
                b.Property<string>("AcademicYear").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Batches");
            });
#pragma warning restore 612, 618
        }
    }
}
