// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shivakala.Infrastructure.Data;

#nullable disable

namespace Shivakala.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ShivakalaDbContext))]
    partial class ShivakalaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Shivakala.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionMarathi")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleMarathi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Strong conceptual coaching for classes 8 to 10 with daily practice, tests, and mentorship.",
                            DescriptionMarathi = "इयत्ता ८ वी ते १० वी साठी दैनंदिन सराव, चाचण्या आणि मार्गदर्शनासह मजबूत पाया घडवणारे प्रशिक्षण.",
                            DisplayOrder = 1,
                            DurationMonths = 12,
                            IsFeatured = true,
                            Slug = "foundation-batch",
                            Standard = "8th - 10th",
                            Title = "Foundation Batch",
                            TitleMarathi = "फाउंडेशन बॅच"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exam-focused batch for SSC students with revision plans, paper solving, and result tracking.",
                            DescriptionMarathi = "एसएससी विद्यार्थ्यांसाठी पुनरावृत्ती योजना, पेपर सोडवणे आणि निकाल विश्लेषणासह परीक्षा-केंद्रित बॅच.",
                            DisplayOrder = 2,
                            DurationMonths = 10,
                            IsFeatured = true,
                            Slug = "board-excellence",
                            Standard = "10th SSC",
                            Title = "Board Excellence Program",
                            TitleMarathi = "बोर्ड उत्कृष्टता कार्यक्रम"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dedicated advanced coaching for Mathematics and Science with doubt-solving labs.",
                            DescriptionMarathi = "गणित आणि विज्ञान विषयांसाठी विशेष शंका समाधान सत्रांसह प्रगत प्रशिक्षण.",
                            DisplayOrder = 3,
                            DurationMonths = 8,
                            IsFeatured = true,
                            Slug = "science-maths-mastery",
                            Standard = "9th - 10th",
                            Title = "Science & Maths Mastery",
                            TitleMarathi = "सायन्स आणि मॅथ्स मास्टरी"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Reasoning, language, and aptitude sessions tailored for scholarship aspirants.",
                            DescriptionMarathi = "शिष्यवृत्ती विद्यार्थ्यांसाठी रिझनिंग, भाषा आणि अॅप्टिट्यूडचे नियोजित मार्गदर्शन.",
                            DisplayOrder = 4,
                            DurationMonths = 6,
                            IsFeatured = false,
                            Slug = "scholarship-prep",
                            Standard = "5th - 8th",
                            Title = "Scholarship Preparation",
                            TitleMarathi = "शिष्यवृत्ती तयारी"
                        });
                });

            modelBuilder.Entity("Shivakala.Core.Entities.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enquiries", (string)null);
                });

            modelBuilder.Entity("Shivakala.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
